---
name: kyverno-policy-test
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: Install Kyverno CLI
        uses: kyverno/action-install-cli@fcee92fca5c883169ef9927acf543e0b5fc58289 # 0.2.0
        with:
          release: "v1.12.6"
      - name: Check install
        run: kyverno version
      - name: Test all pre-defined cases
        run: kyverno test .
