---
name: kyverno-policy-update
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
permissions:
  contents: write
  pull-requests: write
env:
  YAMLFMT_VERSION: 0.13.0
jobs:
  update-policies:
    strategy:
      matrix:
        policies:
          - pod-security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: Checkout Kyverno policies
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
        with:
          repository: kyverno/policies
          path: kyverno-policies-source
      - name: Copy Kyverno policies
        run: |
          rm -rf "${{ matrix.policies }}"
          cp -r "kyverno-policies-source/${{ matrix.policies }}" .
          rm -rf kyverno-policies-source
      - name: Cleanup coppied Kyverno policies
        run: |
          find "${{ matrix.policies }}" -type d -name .chainsaw-test -exec rm -rv {} +
          find "${{ matrix.policies }}" -type f -name artifacthub-pkg.yml -exec rm {} +
      - name: Install yamlfmt
        working-directory: /tmp
        run: |
          curl -sfL "https://github.com/google/yamlfmt/releases/download/v${YAMLFMT_VERSION}/yamlfmt_${YAMLFMT_VERSION}_Linux_x86_64.tar.gz" -o yamlfmt.tar.gz
          tar -zxf yamlfmt.tar.gz
          sudo mv yamlfmt /usr/local/bin/yamlfmt
          rm -rf yamlfmt.tar.gz
      - name: Format Kyverno policies
        run: |
          yamlfmt "${{ matrix.policies }}"
      - name: Create pull request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # 7.0.8
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          branch: "${{ matrix.policies }}-src"
          delete-branch: true
          commit-message: "update ${{ matrix.policies }} policies"
          title: "Update ${{ matrix.policies }} policies"
          body: |-
            Update Kyverno policy ${{ matrix.policies }} from upstream [source repository](https://github.com/kyverno/policies).
